FROM node:18

# WORKDIR /vue-app

# COPY ./vue-app/package*.json .

# RUN npm i

# COPY ./vue-app/public ./public
# COPY ./vue-app .

# RUN npm run dev -- --port 8080

EXPOSE 8080

# CMD [ "npm", "run", "dev", "--port", "8080" ]